import { Nunito_Sans } from 'next/font/google'
import Header from './component/Header'
import './globals.css'

const Nunito = Nunito_Sans({
  weight: ['400', '600', '700'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'LeoPixel',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={Nunito.className} >
        <Header />
        <main className='mx-auto font-extrabold'>{children}</main>
      </body>
    </html>
  )
}
